In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
oss_demo = pd.read_csv('../data/RCS_Households_Demographics.csv')

In [30]:
oss_demo.shape

(50553, 8)

In [31]:
oss_demo.head()

,Household_Index,Date_Added,Housing_Type,Household_Type,Household_Size,Annual_Income,ZIP_Code,ObjectId
0,6096,2018/09/11 23:41:00+00,Own,Single Person,1,"$13,152.00",40214.0,1
1,10233,2018/09/24 21:28:00+00,Rent/Non-Subsidized,Single Parent Female,2,$0.00,40210.0,2
2,10234,2018/09/24 21:28:00+00,Own,Single Parent Female,3,"$12,456.00",40211.0,3
3,10238,2018/09/24 21:30:00+00,Own,Single Parent Female,1,"$10,356.00",40299.0,4
4,10239,2018/09/24 21:30:00+00,Rent/Subsidized,Single Parent Female,2,"$20,672.52",40216.0,5

In [32]:
oss_demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50553 entries, 0 to 50552
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Household_Index  50553 non-null  object
 1   Date_Added       47525 non-null  object
 2   Housing_Type     49409 non-null  object
 3   Household_Type   50553 non-null  object
 4   Household_Size   50553 non-null  int64
 5   Annual_Income    47677 non-null  object
 6   ZIP_Code         49613 non-null  float64
 7   ObjectId         50553 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 3.1+ MB

In [35]:
oss_demo.columns

Index(['Household_Index', 'Date_Added', 'Housing_Type', 'Household_Type',
       'Household_Size', 'Annual_Income', 'ZIP_Code', 'ObjectId'],
      dtype='object')

In [36]:
oss_demo = oss_demo.drop(['Household_Index'], axis=1)

In [37]:
oss_demo = oss_demo.drop(['ObjectId'], axis=1)

In [38]:
oss_demo.columns

Index(['Date_Added', 'Housing_Type', 'Household_Type', 'Household_Size',
       'Annual_Income', 'ZIP_Code'],
      dtype='object')

In [39]:
oss_demo.isna().sum()

Date_Added        3028
Housing_Type      1144
Household_Type       0
Household_Size       0
Annual_Income     2876
ZIP_Code           940
dtype: int64

In [40]:
oss_demo = oss_demo.dropna(subset=['ZIP_Code'])

In [41]:
oss_demo.isna().sum()

Date_Added        3028
Housing_Type       353
Household_Type       0
Household_Size       0
Annual_Income     2101
ZIP_Code             0
dtype: int64

In [42]:
duplicated_mask = oss_demo.duplicated(keep=False)
duplicated_rows = oss_demo[duplicated_mask]
duplicated_rows

,Date_Added,Housing_Type,Household_Type,Household_Size,Annual_Income,ZIP_Code
5568,2018/11/07 00:57:00+00,Rent/Subsidized,Single Person,1,0.0,40203.0
5570,2018/11/07 00:57:00+00,Rent/Subsidized,Single Person,1,0.0,40203.0
11498,2019/01/23 04:13:00+00,Rent/Non-Subsidized,Single Person,1,0.0,40218.0
11502,2019/01/23 04:13:00+00,Rent/Non-Subsidized,Single Person,1,0.0,40218.0
37070,2021/06/04 18:31:00+00,Rent/Non-Subsidized,Single Person,1,0.0,40214.0
...,...,...,...,...,...,...
50498,NaN,NaN,Lives alone,1,NaN,40228.0
50537,NaN,NaN,Lives with spouse,2,NaN,40245.0
50538,NaN,NaN,Lives with spouse,2,NaN,40245.0
50543,NaN,NaN,Lives alone,1,NaN,40218.0
50544,NaN,NaN,Lives alone,1,NaN,40218.0

In [47]:
oss_demo['Date_Added'] = pd.to_datetime(oss_demo['Date_Added'])

In [48]:
oss_demo['Annual_Income'] = oss_demo['Annual_Income'].replace(r'[\$,]', '', regex=True).astype(float)

In [49]:
oss_demo['ZIP_Code'] = oss_demo['ZIP_Code'].astype(int)

In [50]:
oss_demo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49613 entries, 0 to 50552
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date_Added      46585 non-null  datetime64[ns, UTC]
 1   Housing_Type    49260 non-null  object
 2   Household_Type  49613 non-null  object
 3   Household_Size  49613 non-null  int64
 4   Annual_Income   47512 non-null  float64
 5   ZIP_Code        49613 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(1), int64(2), object(2)
memory usage: 2.6+ MB