In [46]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [47]:
oss_demo = pd.read_csv('../data/Raw/RCS_Households_Demographics.csv')

In [48]:
oss_demo.shape

(50553, 8)

In [49]:
oss_demo.head()

,Household_Index,Date_Added,Housing_Type,Household_Type,Household_Size,Annual_Income,ZIP_Code,ObjectId
0,6096,2018/09/11 23:41:00+00,Own,Single Person,1,"$13,152.00",40214.0,1
1,10233,2018/09/24 21:28:00+00,Rent/Non-Subsidized,Single Parent Female,2,$0.00,40210.0,2
2,10234,2018/09/24 21:28:00+00,Own,Single Parent Female,3,"$12,456.00",40211.0,3
3,10238,2018/09/24 21:30:00+00,Own,Single Parent Female,1,"$10,356.00",40299.0,4
4,10239,2018/09/24 21:30:00+00,Rent/Subsidized,Single Parent Female,2,"$20,672.52",40216.0,5

In [50]:
oss_demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50553 entries, 0 to 50552
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Household_Index  50553 non-null  object
 1   Date_Added       47525 non-null  object
 2   Housing_Type     49409 non-null  object
 3   Household_Type   50553 non-null  object
 4   Household_Size   50553 non-null  int64
 5   Annual_Income    47677 non-null  object
 6   ZIP_Code         49613 non-null  float64
 7   ObjectId         50553 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 3.1+ MB

In [51]:
oss_demo.columns

Index(['Household_Index', 'Date_Added', 'Housing_Type', 'Household_Type',
       'Household_Size', 'Annual_Income', 'ZIP_Code', 'ObjectId'],
      dtype='object')

In [52]:
oss_demo = oss_demo.drop(['Household_Index', 'Housing_Type'], axis=1)

In [53]:
oss_demo.columns

Index(['Date_Added', 'Household_Type', 'Household_Size', 'Annual_Income',
       'ZIP_Code', 'ObjectId'],
      dtype='object')

In [54]:
oss_demo.isna().sum()

Date_Added        3028
Household_Type       0
Household_Size       0
Annual_Income     2876
ZIP_Code           940
ObjectId             0
dtype: int64

In [55]:
oss_demo = oss_demo.dropna(subset=['ZIP_Code'])

In [56]:
oss_demo.isna().sum()

Date_Added        3028
Household_Type       0
Household_Size       0
Annual_Income     2101
ZIP_Code             0
ObjectId             0
dtype: int64

In [57]:
duplicated_mask = oss_demo.duplicated(keep=False)
duplicated_rows = oss_demo[duplicated_mask]
duplicated_rows

Empty DataFrame
Columns: [Date_Added, Household_Type, Household_Size, Annual_Income, ZIP_Code, ObjectId]
Index: []

In [58]:
oss_demo['Date_Added'] = pd.to_datetime(oss_demo['Date_Added'])

In [59]:
oss_demo['Annual_Income'] = oss_demo['Annual_Income'].replace(r'[\$,]', '', regex=True).astype(float)

In [60]:
oss_demo['ZIP_Code'] = oss_demo['ZIP_Code'].astype('Int64').astype(str)

In [61]:
oss_demo = oss_demo.rename(columns={'Date_Added': 'date_added', 'Household_Type':'household_type', 'Household_Size':'household_size', 'Annual_Income':'annual_income', 'ZIP_Code':'zipcode', 'ObjectId':'household_id'})

In [62]:
oss_demo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49613 entries, 0 to 50552
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date_added      46585 non-null  datetime64[ns, UTC]
 1   household_type  49613 non-null  object
 2   household_size  49613 non-null  int64
 3   annual_income   47512 non-null  float64
 4   zipcode         49613 non-null  object
 5   household_id    49613 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(1), int64(2), object(2)
memory usage: 2.6+ MB

In [63]:
oss_demo['zipcode'].unique()

array(['40214', '40210', '40211', '40299', '40216', '40212', '40229',
       '40208', '40272', '40243', '40217', '40215', '40209', '40219',
       '40241', '40118', '40203', '40206', '40258', '40218', '40223',
       '40220', '40242', '40291', '40222', '40213', '40290', '40204',
       '40202', '40207', '40245', '40205', '40228', '40252', '40059',
       '40256', '40023', '40251', '40268', '40201', '40177', '40232',
       '40200', '40269', '40047', '40250', '40280', '40150', '40257',
       '42718', '40117', '40224', '40014', '40303', '40273', '40041',
       '40165', '40259', '40227', '40231', '40253', '40226', '40124',
       '40020', '40221', '42017', '47150', '42011', '42010', '40031',
       '40528', '40056', '40018', '40292', '40416', '40114', '47130',
       '40144', '42016', '40160', '40065', '40271', '40042', '42301',
       '40289', '40263', '40109', '42101', '40155', '47129', '40071'],
      dtype=object)

In [64]:
jefferson_co_zips = ['40203', '40210', '40059', '40220', '40041', '40047', '40242',
       '40211', '40215', '40205', '40218', '40222', '40223', '40067',
       '40177', '40212', '40214', '40299', '40245', '40243', '40025',
       '40109', '40241', '40206', '40219', '40258', '40213', '40204',
       '40208', '40216', '40118', '40202', '40217', '40207', '40225',
       '40229', '40023', '40272', '40209', '40228', '40291']

In [65]:
mask = oss_demo['zipcode'].isin(jefferson_co_zips)

In [66]:
oss_demo_filtered = oss_demo[mask]

In [70]:
oss_demo_filtered.to_csv('../data/Clean/clean_oss.csv', index=False)