In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
oss_demo = pd.read_csv('../data/Raw/RCS_Households_Demographics.csv')

In [23]:
oss_demo.shape

(50553, 8)

In [24]:
oss_demo.head()

,Household_Index,Date_Added,Housing_Type,Household_Type,Household_Size,Annual_Income,ZIP_Code,ObjectId
0,6096,2018/09/11 23:41:00+00,Own,Single Person,1,"$13,152.00",40214.0,1
1,10233,2018/09/24 21:28:00+00,Rent/Non-Subsidized,Single Parent Female,2,$0.00,40210.0,2
2,10234,2018/09/24 21:28:00+00,Own,Single Parent Female,3,"$12,456.00",40211.0,3
3,10238,2018/09/24 21:30:00+00,Own,Single Parent Female,1,"$10,356.00",40299.0,4
4,10239,2018/09/24 21:30:00+00,Rent/Subsidized,Single Parent Female,2,"$20,672.52",40216.0,5

In [25]:
oss_demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50553 entries, 0 to 50552
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Household_Index  50553 non-null  object
 1   Date_Added       47525 non-null  object
 2   Housing_Type     49409 non-null  object
 3   Household_Type   50553 non-null  object
 4   Household_Size   50553 non-null  int64
 5   Annual_Income    47677 non-null  object
 6   ZIP_Code         49613 non-null  float64
 7   ObjectId         50553 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 3.1+ MB

In [26]:
oss_demo.columns

Index(['Household_Index', 'Date_Added', 'Housing_Type', 'Household_Type',
       'Household_Size', 'Annual_Income', 'ZIP_Code', 'ObjectId'],
      dtype='object')

In [27]:
oss_demo = oss_demo.drop(['Household_Index', 'Housing_Type'], axis=1)

In [28]:
oss_demo.columns

Index(['Date_Added', 'Household_Type', 'Household_Size', 'Annual_Income',
       'ZIP_Code', 'ObjectId'],
      dtype='object')

In [29]:
oss_demo.isna().sum()

Date_Added        3028
Household_Type       0
Household_Size       0
Annual_Income     2876
ZIP_Code           940
ObjectId             0
dtype: int64

In [30]:
oss_demo = oss_demo.dropna(subset=['ZIP_Code'])

In [31]:
oss_demo.isna().sum()

Date_Added        3028
Household_Type       0
Household_Size       0
Annual_Income     2101
ZIP_Code             0
ObjectId             0
dtype: int64

In [32]:
duplicated_mask = oss_demo.duplicated(keep=False)
duplicated_rows = oss_demo[duplicated_mask]
duplicated_rows

Empty DataFrame
Columns: [Date_Added, Household_Type, Household_Size, Annual_Income, ZIP_Code, ObjectId]
Index: []

In [33]:
oss_demo['Date_Added'] = pd.to_datetime(oss_demo['Date_Added'])

In [34]:
oss_demo['Annual_Income'] = oss_demo['Annual_Income'].replace(r'[\$,]', '', regex=True).astype(float)

In [35]:
oss_demo['ZIP_Code'] = oss_demo['ZIP_Code'].astype(object)

In [36]:
oss_demo = oss_demo.rename(columns={'Date_Added': 'date_added', 'Household_Type':'household_type', 'Household_Size':'household_size', 'Annual_Income':'annual_income', 'ZIP_Code':'zipcode', 'ObjectId':'household_id'})

In [37]:
oss_demo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49613 entries, 0 to 50552
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date_added      46585 non-null  datetime64[ns, UTC]
 1   household_type  49613 non-null  object
 2   household_size  49613 non-null  int64
 3   annual_income   47512 non-null  float64
 4   zipcode         49613 non-null  object
 5   household_id    49613 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(1), int64(2), object(2)
memory usage: 2.6+ MB

In [38]:
oss_demo.to_csv('../data/Clean/clean_oss.csv', index=False)